version: '3.4'

services:
  backend-express:
    container_name: backend-express
    image: backend-express
    build: 
      context: ./backend-express
    environment:
      NODE_ENV: production
      DATABASE_URL: "mysql://admin:password@db:3306/knitto"
    ports:
      - "3000"
      - "9229:9229"
    ## set your startup file here
    networks:
      - primary
    command: ["./wait-for-it.sh","db:3306","--timeout=0","--","yarn","dev"]

  db:
    container_name: db
    image: percona:8.0
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: knitto
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    networks:
      - primary

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080"
    networks:
      - primary

  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - html:/usr/share/nginx/html
    networks:
      - primary
    depends_on:
      - "backend-express"
      - adminer

  frontend-react:
    container_name: frontend-react
    build: 
      context: ./frontend-react
    volumes:
      - html:/usr/src/app/build
    networks:
      - primary
    depends_on:
      - nginx

networks: 
  primary:

volumes:
  html: