version: '3.4'

services:
  backend-express:
    container_name: backend-express
    image: backend-express
    build: 
      context: ./backend-express
    environment:
      NODE_ENV: development
      DATABASE_URL: "mysql://admin:password@db:3306/knitto"
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    networks:
      - primary
    command: ["./wait-for-it.sh","db:3306","--timeout=0","--","yarn","dev"]

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: knitto
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    networks:
      - primary

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - primary

networks: 
  primary: